name: build java_zulu

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 1,15 * *" # bi-weekly on 1st and 15th calendar day at 17:00
  push:
    branches:
      - main

permissions:
  actions: read
  packages: write

jobs:
  push:
    name: "pterodactyl-images:java_17_zulu"
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout for Github repository workspace
        uses: actions/checkout@v3

      - name: Setup QEMU for multiarch builds
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: "v0.10.4"
          buildkitd-flags: --debug

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ghcr.io/multithefranky/wortenia:java_17_zulu